#include <iostream>
using namespace std;

char box2 = 177;
char a = 219;
int main()
{
    cout << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 <<box2 <<box2 <<box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 <<box2 <<box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 <<box2 <<box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 <<box2 <<box2 <<box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 <<box2 <<box2 << endl;
    cout << box2 << box2 << box2 <<"                                                                                             " << box2 << box2 << box2 <<endl;
    cout                      <<"       " << a << a << a << a << a << a << a << a  <<" "  << a << a << a << a << a << a << a << a  <<" " << a << a << a << a << a << a << a << a  <<" " << a << a << a << a << a << a << a << a <<"    "  << a << a << a << a << a << a << a << a << a << a  <<" "  << a << a << a << a << a << a << a << a  <<" "  << a << a << a << a << a << a <<"  "    << a << a  <<" "  << a << a << a << a << a << a   <<" "  << a << a << a << a << a << a << a << a                << endl;
    cout                      <<"       " << a << a  <<"      "                    <<" "  << a << a <<"    "            << a << a  <<" " << a << a <<"      "                     <<" " <<"   "        << a << a        <<"   " <<"    "  << a << a     <<"  " <<a <<a     <<"  " << a << a  <<" "  << a << a <<"    "            << a << a  <<" "  << a << a <<"  "    << a << a <<"  "    << a << a  <<" "   <<"  "   << a << a    <<"  "   <<" "  << a << a <<"    "            << a << a                << endl;
    cout                      <<"       " << a << a << a << a << a << a << a << a  <<" "  << a << a << a << a << a << a << a << a  <<" " << a << a << a << a << a << a << a << a  <<" " <<"   "        << a << a        <<"   " <<"    "  << a << a     <<"  " <<a <<a     <<"  " << a << a  <<" "  << a << a << a << a << a << a << a << a  <<" "  << a << a <<"  "    << a << a <<"  "    << a << a  <<" "   <<"  "   << a << a    <<"  "   <<" "  << a << a << a << a << a << a << a << a                << endl;
    cout                      <<"       " << a << a  <<"      "                    <<" "  << a << a <<"    "            << a << a  <<" " <<"      "                    << a << a  <<" " <<"   "        << a << a        <<"   " <<"    "  << a << a     <<"  " <<a <<a     <<"  " << a << a  <<" "  << a << a <<"    "            << a << a  <<" "  << a << a <<"  "    << a << a <<"  "    << a << a  <<" "   <<"  "   << a << a    <<"  "   <<" "  << a << a <<"    "            << a << a                << endl;
    cout                      <<"       " << a << a  <<"      "                    <<" "  << a << a <<"    "            << a << a  <<" " << a << a << a << a << a << a << a << a  <<" " <<"   "        << a << a        <<"   " <<"    "  << a << a     <<"  " <<a <<a     <<"  " << a << a  <<" "  << a << a <<"    "            << a << a  <<" "  << a << a <<"  "    << a << a << a << a << a << a  <<" "  << a << a << a << a << a << a   <<" "  << a << a <<"    "            << a << a                << endl;
    cout << box2 << box2 << box2 <<"                                                                                             " << box2 << box2 << box2 <<endl;
    cout << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 <<box2 <<box2 <<box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 <<box2 <<box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 <<box2 <<box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 <<box2 <<box2 <<box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 << box2 <<box2 <<box2 << endl;
    
}