#include <iostream>
#include <windows.h>
using namespace std;

int main()
{
    char a = 219;
    cout << "                                                                                                      " << endl;
    cout << "                                                                                                      " << endl;
    cout << "                   " << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << "  " << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a      << "  "   << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a  <<"  "   << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a  <<endl;                                                                      
    cout << "                   " << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << "  " << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a      << "  "   << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a  <<"  "   << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a  <<endl;                                                                   
    cout << "                   " << a << a << a <<"                "                                                          << a << a << a <<"           "<< a << a << a                                              << "  "   <<a <<a <<a <<"                       "                                                                               << a << a << a                                                 <<endl;        
    cout << "                   " << a << a << a <<"                "                                                          << a << a << a <<"           "<< a << a << a                                              << "  "   <<a <<a <<a <<"                       "                                                                               << a << a << a                                                 <<endl;
    cout << "                   " << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a        << "    "  << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a      << "  "   << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a<<"         "                     << a << a << a                                                 <<endl;
    cout << "                   " << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a        << "    "  << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a      << "  "   << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a<<"         "                     << a << a << a                                                 <<endl;    
    cout << "                   " << a << a << a <<"                "                                                          << a << a << a <<"           "<< a << a << a << "                "                                  <<a <<a <<a <<"         "                                                                                             << a << a << a                                                 <<endl;                                                  
    cout << "                   " << a << a << a <<"                "                                                          << a << a << a <<"           "<< a << a << a << "                "                                  <<a <<a <<a <<"         "                                                                                             << a << a << a                                                 <<endl;
    cout << "                   " << a << a << a <<"                "                                                          << a << a << a <<"           "<< a << a << a << "  "                                                << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a <<"         "                    << a << a << a                                                 <<endl;                   
    cout << "                   " << a << a << a <<"                "                                                          << a << a << a <<"           "<< a << a << a << "  "                                                << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a <<"         "                    << a << a << a                                                 <<endl;
    cout << "                                                                                                      " << endl;
    cout << "                   " << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a <<"  "        << a << a << a << a << a << a << a << a << a << a << a << a << a << a  <<"  " <<a <<a <<a <<a <<a <<a <<a <<a<<a <<"   "  <<a <<a <<a   << "  " <<a <<a <<a <<a <<a <<a <<a <<a <<a <<a <<a <<a <<a   << "  "     << a << a << a << a << a << a << a << a << a << a << a << a << a << a     << endl;
    cout << "                   " << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a << a <<"  "        << a << a << a << a << a << a << a << a << a << a << a << a << a << a  <<"  " <<a <<a <<a <<a <<a <<a <<a <<a <<a <<"   " <<a <<a <<a   << "  " <<a <<a <<a <<a <<a <<a <<a <<a <<a <<a <<a <<a <<a   << "  "     << a << a << a << a << a << a << a << a << a << a << a << a << a << a     << endl;
    cout << "                   " << a << a << a <<"    "<< a << a << a << a <<"    "  << a << a << a                       <<"  "        << a << a << a <<"        "<< a << a << a                              <<"  " <<a <<a <<a <<"   " <<a <<a <<a <<"   " <<a <<a <<a       << "       "  <<a <<a <<a   << "       "                                  << a << a << a <<"        "<< a << a << a                                 << endl;
    cout << "                   " << a << a << a <<"    "<< a << a << a << a <<"    "  << a << a << a                       <<"  "        << a << a << a <<"        "<< a << a << a                              <<"  " <<a <<a <<a <<"   " <<a <<a <<a <<"   " <<a <<a <<a       << "       "  <<a <<a <<a   << "       "                                  << a << a << a <<"        "<< a << a << a                                 << endl;
    cout << "                   " << a << a << a <<"    "<< a << a << a << a <<"    "  << a << a << a                       <<"  "        << a << a << a << a << a << a << a << a << a << a << a << a << a << a  <<"  " <<a <<a <<a <<"   " <<a <<a <<a <<"   " <<a <<a <<a       << "       "  <<a <<a <<a   << "       "                                  << a << a << a << a << a << a << a << a << a << a << a << a << a << a     << endl;
    cout << "                   " << a << a << a <<"    "<< a << a << a << a <<"    "  << a << a << a                       <<"  "        << a << a << a << a << a << a << a << a << a << a << a << a << a << a  <<"  " <<a <<a <<a <<"   " <<a <<a <<a <<"   " <<a <<a <<a       << "       "  <<a <<a <<a   << "       "                                  << a << a << a << a << a << a << a << a << a << a << a << a << a << a     << endl;
    cout << "                   " << a << a << a <<"    "<< a << a << a << a <<"    "  << a << a << a                       <<"  "        << a << a << a <<"        "<< a << a << a                              <<"  " <<a <<a <<a <<"   " <<a <<a <<a <<"   " <<a <<a <<a       << "       "  <<a <<a <<a   << "       "                                  << a << a << a <<"        "<< a << a << a                                 << endl;
    cout << "                   " << a << a << a <<"    "<< a << a << a << a <<"    "  << a << a << a                       <<"  "        << a << a << a <<"        "<< a << a << a                              <<"  " <<a <<a <<a <<"   " <<a <<a <<a <<"   " <<a <<a <<a       << "       "  <<a <<a <<a   << "       "                                  << a << a << a <<"        "<< a << a << a                                 << endl;
    cout << "                   " << a << a << a <<"    "<< a << a << a << a <<"    "  << a << a << a                       <<"  "        << a << a << a <<"        "<< a << a << a                              <<"  " <<a <<a <<a <<"   " <<a <<a <<a <<a <<a <<a <<a <<a <<a   << "  " <<a <<a <<a <<a <<a <<a <<a <<a <<a <<a <<a <<a <<a   << "  "     << a << a << a <<"        "<< a << a << a                                 << endl;
    cout << "                   " << a << a << a <<"    "<< a << a << a << a <<"    "  << a << a << a                       <<"  "        << a << a << a <<"        "<< a << a << a                              <<"  " <<a <<a <<a <<"   " <<a <<a <<a <<a <<a <<a <<a <<a <<a   << "  " <<a <<a <<a <<a <<a <<a <<a <<a <<a <<a <<a <<a <<a   << "  "     << a << a << a <<"        "<< a << a << a                                 << endl;

}